#!/bin/busybox ash
. /etc/init.d/tc-functions
useBusybox

PATH="/bin:/sbin:/usr/bin:/usr/sbin"
export PATH
umask 022

DEVROOT="/dev"

# Create a list of fdisk -l
FDISKL=`fdisk -l | awk '$1 ~ /dev/{printf " %s ",$1}'`

# Loop through block devices
for i in `find /sys/block/*/ -mindepth 1 -maxdepth 1 -name dev`; do
  case "$i" in
    *loop*|*ram*)
      continue
      ;;
  esac

  DEVNAME=`echo "$i"| tr [!] [/] | awk 'BEGIN{FS="/"}{print $(NF-1)}'`
  DEVMAJOR="$(cat $i|cut -f1 -d:)"
  [ "$DEVMAJOR" != '8' ] && continue
  if [ -z $FSTYPE ]; then
    for PART in $FDISKL; do
      case "$PART" in 
        *"$DEVROOT/$DEVNAME"*) 
          FSTYPE="$(fstype $PART)"
          MOUNTPOINT=`echo $PART | sed -e "s:.*\($DEVNAME.*\):/mnt/\1:g"`
          [ -d $MOUNTPOINT ] || mkdir $MOUNTPOINT
          [ $(mount | grep -q $PART) ] || mount $PART $MOUNTPOINT 
          break
          ;;
      esac 
    done
  fi
  [ -n "$FSTYPE" ] && continue

  # Ok, we now have an uninitialised disk. Partition and format it
  printf "Creating partition table on $DEVROOT/$DEVNAME\n"
  DEVNAME1=${DEVNAME}1
  fdisk $DEVROOT/$DEVNAME << EOF > /dev/null 2>&1
n
p
1


w
EOF
  printf "Formating $DEVROOT/$DEVNAME1 as EXT4\n"
  mkfs.ext4 $DEVROOT/$DEVNAME1
  mkdir -p /mnt/$DEVNAME1
  printf "Mounting $DEVROOT/$DEVNAME1 on /mnt/$DEVNAME1\n"
  mount $DEVROOT/$DEVNAME1 /mnt/$DEVNAME1
done

