#! /bin/sh
# Busybox ash not supported. Use posix SH and disable a couple of
# ash extensions I use
#
# shellcheck shell=sh
# shellcheck disable=SC2039

if [ -f "$(dirname "$0")/dsas_common.sh" ]; then
  # Only the $LOG variable is needed
  # shellcheck source=append/usr/local/sbin/dsas_common.sh
  . "$(dirname "$0")/dsas_common.sh"
else
  echo "Common functions not found !!"
  exit 1
fi

# Maximum number of logs to keep
rotatemax=9

rotate_logs() {
  [ -f "${1}.$rotatemax" ] && /bin/rm "${1}.$rotatemax"
  for i in $(seq $rotatemax -1 2); do
    [ -f "${1}.$((i-1))" ] && /bin/mv "${1}.$((i-1))" "${1}.$i"
  done
  [ -f "${1}" ] && /bin/mv "${1}" "${1}.1"
  touch "${1}"
}

if [ "$#" -gt 0 ]; then
  for logfile in "$@"; do
    rotate_logs "$logfile"
  done
else
  while IFS= read -r -d '' logfile; do
    rotate_logs "$logfile"
  done < <(find "$LOG" -maxdepth 1 -name "*.log" -print0)
fi

# Post rotate, need to send lighttpd a HUP so that the web error and access
# logs are be found by the web server
pkill -HUP lighttpd